/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-25 14:52:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class librarySystem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Library System JSP</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <h4>Link to: <a href=\"./index.jsp\">Loan System</a></h4>\n");
      out.write("        \n");
      out.write("        <h2>Library System</h2>\n");
      out.write("        <h3> Display Books in Library </h3>\n");
      out.write("        <form action=\"LibrarySystemController\" method=\"GET\">\n");
      out.write("            View All Books: <input type=\"submit\" name=\"library\" value=\"displayAll\"/><br>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <form action=\"LibrarySystemController\" method=\"GET\">\n");
      out.write("            View Book with ID:<input type=\"text\" name=\"viewBookID\">\n");
      out.write("            <input type=\"submit\" name=\"library\" value=\"displayBook\"/><br>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <h3>Add Book to Library</h3>\n");
      out.write("        <form action=\"LibrarySystemController\" method=\"POST\">\n");
      out.write("            Title <input type=\"text\" name=\"title\"><br>\n");
      out.write("            Description <input type=\"text\" name=\"description\"><br>\n");
      out.write("            ISBN <input type=\"text\" name=\"isbn\"><br>\n");
      out.write("            Author <input type=\"text\" name=\"author\"><br>\n");
      out.write("            Publisher <input type=\"text\" name=\"publisher\"><br>\n");
      out.write("            Call Number <input type=\"text\" name=\"callNumber\"><br>\n");
      out.write("            <input type=\"submit\" name=\"library\" value=\"addBook\"/>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <h3>Update Book in Library </h3>\n");
      out.write("        <form action=\"LibrarySystemController\" method=\"POST\">\n");
      out.write("            Book ID <input type=\"text\" name=\"bookID\"><br>\n");
      out.write("            Title <input type=\"text\" name=\"title\"><br>\n");
      out.write("            Description <input type=\"text\" name=\"description\"><br>\n");
      out.write("            ISBN <input type=\"text\" name=\"isbn\"><br>\n");
      out.write("            Author <input type=\"text\" name=\"author\"><br>\n");
      out.write("            Publisher <input type=\"text\" name=\"publisher\"><br>\n");
      out.write("            Call Number <input type=\"text\" name=\"callNumber\"><br>\n");
      out.write("            <input type=\"submit\" name=\"library\" value=\"updateBook\"/>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        <h3>Delete a Book</h3>\n");
      out.write("        <form action=\"LibrarySystemController\" method=\"GET\">\n");
      out.write("            Delete book with BookID:<input type=\"text\" name=\"deleteBookID\">\n");
      out.write("            <input type=\"submit\" name=\"library\" value=\"deleteBook\"/><br>\n");
      out.write("        </form>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
